name: Benchmark

on:
  pull_request:
    paths:
      - "benchmarks/**" # Trigger if any file in the benchmarks folder is modified

jobs:
  run-benchmarks:
    runs-on: ubuntu-latest
    if: github.event.pull_request
    env:
      JDK_JAVA_OPTIONS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # JDK_JAVA_OPTIONS is _the_ env. variable to use for modern Java
      SBT_OPTS: -XX:+PrintCommandLineFlags -Xms6G -Xmx6G -Xss4M -XX:+UseG1GC -XX:ReservedCodeCacheSize=512M -XX:NonProfiledCodeHeapSize=256M # Needed for sbt
      NODE_OPTIONS: --max_old_space_size=6144
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Cache SBT dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.sbt
            ~/.ivy2/cache
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}

      - name: Run JMH Benchmarks
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})
          echo "Changed files: $changed_files"
          for file in $changed_files; do
            if [[ "$file" == benchmarks/**/*.scala ]]; then
              sbt "jmh:run -i 10 -wi 10 -f1 -t1" | tee benchmark-results.txt
              break
            fi
          done

      - name: Upload Benchmark Results
        uses: actions/upload-artifact@v3
        with:
          name: benchmark-results
          path: benchmark-results.txt

      - name: Post Benchmark Results as PR Comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const benchmarkResults = fs.readFileSync('benchmark-results.txt', 'utf8');
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `## Benchmark Results\n\n\`\`\`\n${benchmarkResults}\n\`\`\``
            });
