# Benchmark workflow for ZIO Semaphore
name: ZIO Benchmarks

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
    branches-ignore:
      - gh-pages
    paths:
      - "benchmarks/src/main/scala/zio/stm/SemaphoreBenchmark.scala" # Only trigger if SemaphoreBenchmark changes
      - "core/shared/src/main/scala/zio/Semaphore.scala"
      - "core/shared/src/main/scala/zio/stm/TSemaphore.scala" # Optional: Include TSemaphore changes too

    # Prevent concurrent builds on the same branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) && github.run_id || github.ref }}
  cancel-in-progress: true

permissions:
  # Allow access to GitHub pages and content updates
  deployments: write
  contents: write

jobs:
  benchmark:
    name: Run Semaphore Benchmark
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: temurin
          java-version: 17
          check-latest: true

      - name: Use CI sbt jvmopts
        run: |
          mv .jvmopts .jvmopts_old
          mv .jvmopts-ci .jvmopts
          cat .jvmopts

      - name: Compile project
        run: sbt compile

      - name: Run Semaphore Benchmarks
        # JMH options:
        # -wi 5: 5 warmup iterations
        # -i 5: 5 benchmark iterations
        # -r 1: Minimum time per measurement iteration (1 second)
        # -w 1: Minimum time per warmup iteration (1 second)
        # -t 1: Run with 1 thread
        # -rf json: Output results in JSON format
        # -to 120: Timeout per iteration (120 seconds)
        run: sbt "benchmarks/jmh:run -wi 5 -i 5 -r 1 -w 1 -t 1 -to 120 -rf json -foe true"

      - name: Cache benchmark data
        uses: actions/cache@v3
        with:
          path: ./cache
          key: ${{ runner.os }}-benchmark

      - name: Rollback JVM options
        run: |
          mv .jvmopts .jvmopts-ci
          mv .jvmopts_old .jvmopts
          cat .jvmopts

      - name: Upload Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1.20.3
        with:
          name: Semaphore JMH Benchmark
          tool: "jmh"
          output-file-path: benchmarks/target/jmh-result.json
          # Access token to push updates
          # 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
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          # Automatically push and deploy to GitHub pages branch for benchmarking results
          auto-push: true
          alert-threshold: "200%" # Alert if performance changes by more than 200%
          comment-on-alert: true # Post a comment on the PR if there's a performance alert
          fail-on-alert: true # Fail the workflow if there's a performance regression
          alert-comment-cc-users: "@varshith257"
